-- Mở PDB trước khi tạo user
ALTER SESSION SET CONTAINER = XEPDB1;

-- Tạo user ứng dụng
CREATE USER dongnt IDENTIFIED BY dongcopper80;
GRANT CONNECT, RESOURCE TO dongnt;
ALTER USER dongnt QUOTA UNLIMITED ON USERS;

-- Set NLS_CALENDAR cho instance
ALTER SYSTEM SET NLS_CALENDAR = 'GREGORIAN' SCOPE=SPFILE;