services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - ELASTIC_PASSWORD=dongcopper80  # password cho user "elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-s", "-u", "elastic:dongcopper80", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - my_network

volumes:
  es_data:

networks:
  my_network: # Custom network definition (optional)
    driver: bridge